[package]
name = "part_1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
expect-test = "1.4.1"
strum = "0.25.0"
strum_macros = "0.25.3"
thiserror = "1.0.50"
